#  Main header!
#  Line 2

[songs]
	[songs.harbinger_theme]
		triggers = [ "Mob-harbinger_theme" ]

[triggers]
	[triggers.mob]
		identifier = "harbinger_theme"
		mob_nbt = [ ]
		mob_targeting = false
		play_when_paused = true
		resource_matcher = "exact"
		resource_name = [ "cataclysm:the_harbinger" ]
		target_any_player = false
	[triggers.universal]
		active_cooldown = "0"
		fade_in = "0"
		fade_out = "0"
		persistence = "0"
		ticks_before_active = "0"
		ticks_before_audio = "0"
		ticks_between_audio = "0"

