name = "The New Tumblr Bumblr"
author = "SpookiestOfSquid"
version = "0.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6350d7b4b963cf7943dae93978366043833731f5629a2542d9422b24f9ffb82"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
