name = "The New Tumblr Bumblr"
author = "SpookiestOfSquid"
version = "0.16.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7816f3bf02393163d6f202f3ee1c5e7bd87073a9c0d084a75a15b72ba04d50c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
