name = "The New(er) Tumblr Bumblr"
author = "SpookiestOfSquid"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e9911735a6ed9623b5cade64f6df90f1855799ea02582d0f467d8a6a0239e99"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
