
[general]
	#Display which mod adds the enchantment on ancient books.
	showAddedByTooltip = true
	#How fast items will switch in the enchanting table tooltip (in milliseconds).
	itemCarouselSpeed = 700

