version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
azurelib = true
farmersdelight = true
mob_grinding_utils = true
createtransmission = true
goety = true
silentgear = true
golemoverhaul = true
refurbished_furniture = true
copycats = true
ntgl = true
irons_jewelry = true
hauntedharvest = true
comforts = true
bfr = true
domum_ornamentum = true
sootychimneys = true
envelope = true
railways = true
bits_n_bobs = true
trmt = true
mynethersdelight = true
ftbquests = true
shippingbin = true
cgs = true
exposure = true
offroad = true
naturalist = true
apotheosis = true
supplementaries = true
createbigcannons = true
vampirism = true
deeperdarker = true
minersdelight = true
endrem = true
create = true
yungscavebiomes = true
minecolonies = true
estrogen = true
rottencreatures = true
visualworkbench = true
createoreexcavation = true
multipiston = true
minecraft = true
occultism = true
create_connected = true
mowziesmobs = true
fdlib = true
azimuth = true
fdbosses = true
create_wizardry = true
werewolves = true
createaddition = true
sophisticatedstorage = true
twilightforest = true
creeperoverhaul = true
waystones = true
apothic_enchanting = true
tradingpost = true
immersiveengineering = true
goetyhostility = true
tide = true
darkerdepths = true
createpropulsion = true
piglinproliferation = true
yagm = true
brewinandchewin = true
quark = true
cataclysm = true
createestrogen = true
irons_spellbooks = true
aquamirae = true
ends_delight = true
create_enchantment_industry = true
simplylight = true
monobank = true
mekanismgenerators = true
amendments = true
eclipticseasons = true
ender_trigon_unofficial = true
moonlight = true
pet_home = true
relics = true
complicated_bees = true
sophisticatedbackpacks = true
create_tweaked_controllers = true
goety_cataclysm = true
enderscape = true
elysium_api = true
incubation = true
vista = true
mekanism = true
structurize = true
aeronautics = true
simulated = true
interiors = true
netherman = true
jadensnetherexpansiondelight = true
struts = true
fairylights = true
create_dragons_plus = true
lootr = true
irons_lib = true
iceandfire = true
cobblegengalore = true
regions_unexplored = true
betterarcheology = true
netherexp = true
ae2 = true
endermanoverhaul = true
primal = true
tea_aroma = true
irons_patreon_lib = true
ad_astra = true
ad_astra_giselle_addon = true
