# ==========================================
# UNIVERSAL SETTINGS
# ==========================================
[universal]
interruptible = false
seamless_handoff = true
interrupt_whitelist = ["test_draugr", "leviathan_phase_2", "leviathan_phase_1", "maledictus_battle", "harbinger_battle", "boss_ender_dragon", "ignis_phase_3", "Luxtructosaurus", "ignis_phase_2", "ignis_phase_1", "enderguardian_phase_2", "scylla_battle", "monstrosity_battle", "enderguardian_phase_1", "remnant_battle"]
cooldown_group_time = "0:10"
cooldown_group_events = ["overworld_game"]

# ==========================================
# EVENTS (TRIGGERS)
# ==========================================
[[events.mobs]]
event_name = "leviathan_phase_2"
priority = 3
fade_in = 0.5
fade_out = 5.0
detection_range = 76.0
nbt_match = ["{MeltDown:1b}"]
resource_name = ["cataclysm:the_leviathan"]


[[events.mobs]]
event_name = "leviathan_phase_1"
priority = 3
fade_out = 0.5
detection_range = 76.0
nbt_match = ["{MeltDown:0b}"]
resource_name = ["cataclysm:the_leviathan"]


[[events.mobs]]
event_name = "maledictus_battle"
priority = 3
fade_out = 5.0
detection_range = 76.0
resource_name = ["cataclysm:maledictus"]


[[events.structure]]
event_name = "in_catacombs"
priority = 2
resource_name = ["irons_spellbooks:catacombs"]


[[events.mobs]]
event_name = "harbinger_battle"
priority = 3
fade_out = 5.0
detection_range = 76.0
nbt_match = ["{Is_Act:1b}"]
resource_name = ["cataclysm:the_harbinger"]


[[events.mobs]]
event_name = "boss_ender_dragon"
priority = 3
detection_range = 192.0
resource_name = ["minecraft:ender_dragon"]


[[events.mobs]]
event_name = "ignis_phase_3"
priority = 3
fade_in = 0.5
fade_out = 5.0
detection_range = 76.0
nbt_match = ["{BossPhase:2}"]
resource_name = ["cataclysm:ignis"]


[[events.mobs]]
event_name = "Luxtructosaurus"
priority = 3
fade_out = 5.0
detection_range = 76.0
resource_name = ["alexscaves:luxtructosaurus"]


[[events.mobs]]
event_name = "ignis_phase_2"
priority = 3
fade_in = 0.5
fade_out = 0.5
detection_range = 76.0
nbt_match = ["{BossPhase:1}"]
resource_name = ["cataclysm:ignis"]


[[events.mobs]]
event_name = "ignis_phase_1"
priority = 3
fade_out = 0.5
detection_range = 76.0
nbt_match = ["{BossPhase:0}"]
resource_name = ["cataclysm:ignis"]


[[events.biomes]]
event_name = "overworld_game"
remember_track = true
resume_from_timestamp = true


[[events.mobs]]
event_name = "enderguardian_phase_2"
priority = 3
fade_in = 0.5
fade_out = 5.0
detection_range = 76.0
nbt_match = ["{is_Helmetless:1b}"]
resource_name = ["cataclysm:ender_guardian"]


[[events.mobs]]
event_name = "scylla_battle"
priority = 3
fade_out = 5.0
detection_range = 76.0
nbt_match = ["{Act:1b}"]
resource_name = ["cataclysm:scylla"]


[[events.mobs]]
event_name = "monstrosity_battle"
priority = 3
detection_range = 76.0
nbt_match = ["{is_Awaken:1b}"]
resource_name = ["cataclysm:netherite_monstrosity"]


[[events.mobs]]
event_name = "enderguardian_phase_1"
priority = 3
fade_out = 0.5
detection_range = 76.0
nbt_match = ["{is_Helmetless:0b}"]
resource_name = ["cataclysm:ender_guardian"]


[[events.mobs]]
event_name = "remnant_battle"
priority = 3
fade_out = 5.0
detection_range = 76.0
nbt_match = ["{has_necklace:1b}"]
resource_name = ["cataclysm:ancient_remnant"]


# ==========================================
# AUDIOS (SONGS)
# ==========================================
[[audios."harbinger_theme"]]
play_once = 1
interruptible = true
interrupt_whitelist = []
target_events = ["harbinger_battle"]

[[audios."scylla_theme"]]
play_once = 1
interruptible = true
interrupt_whitelist = []
target_events = ["scylla_battle"]

[[audios."leviathan_theme_1"]]
play_once = 1
interruptible = true
interrupt_whitelist = []
target_events = ["leviathan_phase_1"]

[[audios."leviathan_theme_2"]]
play_once = 1
interruptible = true
interrupt_whitelist = []
target_events = ["leviathan_phase_2"]

[[audios."monstrosity_theme"]]
play_once = 1
interruptible = true
interrupt_whitelist = []
target_events = ["monstrosity_battle"]

[[audios."remnant_theme"]]
play_once = 1
interruptible = true
interrupt_whitelist = []
target_events = ["remnant_battle"]

[[audios."maledictus_theme"]]
play_once = 1
interruptible = true
interrupt_whitelist = []
target_events = ["maledictus_battle"]

[[audios."enderguardian_theme_1"]]
play_once = 1
interruptible = true
interrupt_whitelist = []
target_events = ["enderguardian_phase_1"]

[[audios."enderguardian_theme_2"]]
play_once = 1
interruptible = true
interrupt_whitelist = []
target_events = ["enderguardian_phase_2"]

[[audios."minecraft:sounds/music/game/end/boss"]]
play_once = 1
interruptible = true
interrupt_whitelist = []
target_events = ["boss_ender_dragon"]

[[audios."minecraft:sounds/music/game/calm1"]]
interrupt_whitelist = []
biomes = ["werewolves:werewolf_heaven"]
target_events = ["overworld_game"]

[[audios."minecraft:sounds/music/game/calm2"]]
interrupt_whitelist = []
biomes = ["werewolves:werewolf_heaven"]
target_events = ["overworld_game"]

[[audios."minecraft:sounds/music/game/calm3"]]
interrupt_whitelist = []
biomes = ["werewolves:werewolf_heaven"]
target_events = ["overworld_game"]

[[audios."minecraft:sounds/music/game/piano1"]]
interrupt_whitelist = []

[[audios."minecraft:sounds/music/game/piano2"]]
interrupt_whitelist = []
target_events = ["overworld_game"]

[[audios."minecraft:sounds/music/game/piano3"]]
interrupt_whitelist = []
target_events = ["overworld_game"]

[[audios."aria_biblio"]]
interrupt_whitelist = []

[[audios."silence"]]
interrupt_whitelist = []
target_events = ["overworld_game", "in_catacombs"]

[[audios."alexscaves:sounds/music/lux"]]
play_once = 1
interruptible = true
interrupt_whitelist = []
target_events = ["Luxtructosaurus"]

[[audios."ignis_theme_1"]]
play_once = 1
interruptible = true
interrupt_whitelist = []
target_events = ["ignis_phase_1"]

[[audios."ignis_theme_2"]]
play_once = 1
interruptible = true
interrupt_whitelist = []
target_events = ["ignis_phase_2"]

[[audios."ignis_theme_3"]]
play_once = 1
interruptible = true
interrupt_whitelist = []
target_events = ["ignis_phase_3"]

[[audios."minecraft:sounds/music/game/piano1"]]
interrupt_whitelist = []
target_events = ["overworld_game"]

[[audios."minecraft:sounds/music/game/hal1"]]
interrupt_whitelist = []
target_events = ["overworld_game"]

[[audios."minecraft:sounds/music/game/hal2"]]
interrupt_whitelist = []
target_events = ["overworld_game"]

[[audios."minecraft:sounds/music/game/hal3"]]
interrupt_whitelist = []
target_events = ["overworld_game"]

[[audios."minecraft:sounds/music/game/hal4"]]
interrupt_whitelist = []
target_events = ["overworld_game"]

[[audios."minecraft:sounds/music/game/nuance1"]]
interrupt_whitelist = []
target_events = ["overworld_game"]

[[audios."minecraft:sounds/music/game/nuance2"]]
interrupt_whitelist = []
target_events = ["overworld_game"]

[[audios."minecraft:sounds/music/game/piano1"]]
interrupt_whitelist = []
biomes = ["minecraft:old_growth_pine_taiga", "minecraft:old_growth_spruce_taiga", "regions_unexplored:blackwood_taiga", "regions_unexplored:boreal_taiga", "regions_unexplored:golden_boreal_taiga", "regions_unexplored:pine_taiga", "regions_unexplored:redwoods", "regions_unexplored:sparse_redwoods", "minecraft:old_growth_birch_forest"]
target_events = ["overworld_game"]

[[audios."minecraft:sounds/music/game/piano1"]]
interrupt_whitelist = []
biomes = ["minecraft:old_growth_pine_taiga", "minecraft:old_growth_spruce_taiga", "regions_unexplored:blackwood_taiga", "regions_unexplored:boreal_taiga", "regions_unexplored:golden_boreal_taiga", "regions_unexplored:pine_taiga", "regions_unexplored:redwoods", "regions_unexplored:sparse_redwoods", "minecraft:old_growth_birch_forest"]
target_events = ["overworld_game"]

